### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by tumic0** [asamm/lomaps-mapsforge#5]
There is no licence for the Mapsforge theme (and other stuff) in this repo. Without a license, one does not only know whether he can use/reuse the stuff but also whether to make pull requests (the theme is e.g. not even a valid Mapsforge render theme at the moment and needs to be fixed).

**Comment by tumic0** [comment]
As there is evidently no interest at all to clarify the licensing, I suggest the Apache license from the theme.xml file:

```xml
<!--
		LOCUS INTERNAL THEME FOR LOMAPS
				Release July, 2016
			Distributed under the Apache License


version 2.4.0
-->
```

applies to the whole theme and I'm closing this issue.

**Comment by voldapet** [comment]
Ahh I'm sorry and thank you for the reminder. The license is defined now... Thank you
